development: &default
  adapter: sqlite3
  database: db/wheeler_board_development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: db/wheeler_board_test.sqlite3

production:
  adapter: postgresql
  database: wheeler_board
  pool: 5
  timeout: 5000
