development:
  adapter: postgresql
  database: wheeler_board
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wheeler_board_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wheeler_board
  pool: 5
  timeout: 5000
