development: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wheeler_board_development
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  <<: *default
  database: wheeler_board_test

production:
  adapter: postgresql
  database: wheeler_board
  pool: 5
  timeout: 5000
